### ISSUE TITLE
Helm Chart deployment

### ISSUE THREAD

**Issue by whur** [langflow-ai/langflow-helm-charts#10]
Can you update the helm chart deployment and version bump? I'm still getting after [#8](https://github.com/langflow-ai/langflow-helm-charts/pull/8) with a fresh install i just started today:

`Helm install failed for release default/langflow-ide with chart langflow-ide@0.0.1: template: langflow-ide/templates/backend-statefulset.yaml:148:35: executing "langflow-ide/templates/backend-statefulset.yaml" at <.Values.zookeeper.volumes.data.existingStorageClassName>: nil pointer evaluating interface {}.volumes`

Please and thank you.

**Comment by hakan-77** [comment]
Versions after 1.0-alpha have some significant changes. Any chance to upgrade soon? or, are we going to wait 1.0.beta? 

BTW, in my case everything installs fine but the frontend cannot reach backend. Error message in UI only, no logs.

**Comment by nicoloboschi** [comment]
Hey @whur and @hakan-77 I'm releasing 0.1.0 for both the charts. 

There's still a bug for the frontend in the ´ide´ chart that needs a fix on the docker image side. 
https://github.com/langflow-ai/langflow/pull/2887

**Comment by whur** [comment]
Does this health check PR fix this issue?
<img width="821" alt="Capture" src="https://github.com/user-attachments/assets/c6a82b83-9e2a-4de1-abff-0e62f0b667d9">

I can't find anything in either pod's logs that identify what's going on.

**Comment by nicoloboschi** [comment]
The specific error is that frontend is checking whether the backend is up or not by calling the health check. Since that endpoint is not reachable it just gets stuck. The request doesn't arrive to the backend at all, so there's no log

**Comment by ragingbal** [comment]
Same issue here with the latest charts on GKE. The backend pod in a crashloop without much in terms of logs. 

Any ETA for fix?

**Comment by whur** [comment]
I'm still getting health check errors on the langflow backend:
```
  Normal   Pulled     17s   kubelet            Container image "langflowai/langflow-backend:1.0.13" already present on machine
  Normal   Created    17s   kubelet            Created container langflow-ide
  Normal   Started    17s   kubelet            Started container langflow-ide
  Warning  Unhealthy  3s    kubelet            Liveness probe failed: Get "http://10.69.1.174:7860/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3s    kubelet            Readiness probe failed: Get "http://10.69.1.174:7860/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)```

**Comment by nicoloboschi** [comment]
Which version are you using?

**Comment by whur** [comment]
I'm using langflow 1.0.13 and helm chart 0.1.0

**Comment by tkdguq05** [comment]
@whur Did upgrading to version 1.0.13 solve the `couldn't estabilish a connect` issue?
I had a same problem on 1.0.11.

**Comment by tkdguq05** [comment]
version 1.0.14 works fine!

**Comment by whur** [comment]
@tkdguq05 no, I still get the health check issues but i have some health check errors on other pods so I can't rule out environment issue at the moment, and I haven't had the time to get into that.

**Comment by hakan-77** [comment]
version 1.0.14 works fine for me too, except, frontend to backend communication with http did not work. I had to use https end to end.  FYI- @whur

**Comment by nicoloboschi** [comment]
@whur @hakan-77 did you have a chance to test this out with 1.0.16? I'd like to close this issue

**Comment by whur** [comment]
> @whur @hakan-77 did you have a chance to test this out with 1.0.16? I'd like to close this issue

i have not, but my issues may be environmental so this can be closed.

**Comment by hakan-77** [comment]
@nicoloboschi I have tested with both 1.0.16 and 1.0.17. Everything works, thank you for the great chart!
